// This file will be generated by the build system with real compiled WASM bytecode
// The build process will create the get_bytes() function that returns the actual
// compiled DustSwap contract bytecode

pub fn get_bytes() -> Vec<u8> {
    // This function will be replaced by build.rs with actual compiled bytecode
    include_bytes!(concat!(env!("OUT_DIR"), "/dust_swap.wasm")).to_vec()
}
