// This file will be generated by the build system with real compiled WASM bytecode
// The build process will create the get_bytes() function that returns the actual
// compiled OrbitalWandFactory contract bytecode

pub fn get_factory_bytes() -> Vec<u8> {
    // This function will be replaced by build.rs with actual compiled bytecode
    include_bytes!(concat!(env!("OUT_DIR"), "/orbital_wand_factory.wasm")).to_vec()
}

pub fn get_wand_template_bytes() -> Vec<u8> {
    // This function will be replaced by build.rs with actual compiled bytecode
    include_bytes!(concat!(env!("OUT_DIR"), "/wand_template.wasm")).to_vec()
}

// Legacy function for backward compatibility
pub fn get_bytes() -> Vec<u8> {
    get_factory_bytes()
}
