[package]
name = "alkane-coupon-template"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
alkanes-support.workspace = true
alkanes-runtime.workspace = true
metashrew-support.workspace = true
anyhow.workspace = true

[features]
debug-log = []